name:
  MAIN CI
  # develop 브랜치에 push가 될 때마다 이 action이 실행됩니다.
on:
  push:
    branches:
      - main
    tags:
      - "production-**"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps: # 1 - 소스코드 복사
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node modules # 2 - node_modules 캐싱
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 3 - 의존성 패키지 설치
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build # 4 - 빌드
        run: npm run build

      - name: Configure AWS Credentials # 5 - AWS 인증
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Backup Current Build in S3 # 6. 현재 빌드 백업
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          aws s3 cp --recursive s3://${{ secrets.AWS_BUCKET_NAME }} s3://${{ secrets.AWS_BUCKET_NAME }}/versions/$TIMESTAMP
          aws s3 cp --recursive s3://${{ secrets.AWS_BUCKET_NAME }} s3://${{ secrets.AWS_BUCKET_NAME }}/versions/latest

      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_NAME }} --delete # 7 - AWS S3에 빌드 결과물 배포        ## CRA로 생성한 React App은 build 폴더에 빌드 결과물이 들어있습니다. (dist 폴더가 아님!)

      - name: Invalidate CloudFront Cache # 8 - CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
