name:
  MAIN CI
  # develop ë¸Œëœì¹˜ì— pushê°€ ë  ë•Œë§ˆë‹¤ ì´ actionì´ ì‹¤í–‰ë©ë‹ˆë‹¤.
on:
  push:
    branches:
      - main
    tags:
      - "production-**"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps: # 1 - ì†ŒìŠ¤ì½”ë“œ ë³µì‚¬
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules # 2 - node_modules ìºì‹±
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 3 - ì˜ì¡´ì„± íŒ¨í‚¤ì§€ ì„¤ì¹˜
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Set Kakao API Key in env.js
        run: |
          echo "ğŸ› ï¸ ì¹´ì¹´ì˜¤ë§µ API í‚¤ë¥¼ env.jsì— ì£¼ì… ì¤‘..."
          sed -i "s|REPLACE_KAKAO_MAP_API_KEY|${{ secrets.KAKAO_MAP_API_KEY }}|" ./public/env.js
          sed -i "s|REPLACE_API_BASE_URL|${{ secrets.API_BASE_URL }}|" ./public/env.js

      - name: Build # 4 - ë¹Œë“œ
        run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload Sentry Release & Sourcemaps
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kakao-tech-bootcamp
          SENTRY_PROJECT: gangazido
          SENTRY_RELEASE: ${{ github.sha }}
        with:
          environment: production
          sourcemaps: ./build/static/js

      - name: Configure AWS Credentials # 5 - AWS ì¸ì¦
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Backup Current Build in S3 # 6. í˜„ì¬ ë¹Œë“œ ë°±ì—…
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          aws s3 cp --recursive s3://${{ secrets.AWS_BUCKET_NAME }} s3://${{ secrets.AWS_BUCKET_NAME }}/versions/$TIMESTAMP
          aws s3 cp --recursive s3://${{ secrets.AWS_BUCKET_NAME }} s3://${{ secrets.AWS_BUCKET_NAME }}/versions/latest

      - name: Deploy to S3 safely (Preserve uploads)
        run: |
          mkdir temp-build
          rsync -a \
            --exclude 'pet/' \
            --exclude 'uploads/user/' \
            ./build/ temp-build/
          aws s3 sync temp-build/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete \
            --exclude 'pet/*' \
            --exclude 'uploads/user/*'

      - name: Invalidate CloudFront Cache # 8 - CloudFront ìºì‹œ ë¬´íš¨í™”
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
